project:
  name: alien
  source_dir: data/alien_sources
  outdir: data/alien_gmt

outputs:
  include_symbols: true

term_id_collisions:
  action: error

sources:
  - type: msigdb_remote
    version: "2026.1"
    db_species: HS
    collection: C2

targets:
  - name: human_gencode49
    type: ensembl_gtf
    annotation:
      source: GENCODE
      version: "49"

runtime:
  workers: 1
